### ISSUE TITLE
fix: Rename ScrollView to `SingleChildScrollView

### ISSUE THREAD

**Issue by divyanshub024** [Securrency-OSS/mirai#250]
**Description**

Right now we `SingleChildScrollView` Parser type is named as `scrollView`. This can be confusing for the new users. It is preferred if we rename it to "singleChildScrollView`.

**Comment by iocampomx** [comment]
Hi @divyanshub024, I'm still confused on this change, I'm using Mirai for the first time. I was following the instructions from the README.md file, and I'm getting this error: `Widget type [singleChildScrollView] not supported`, I had to rename the widget type to `scrollView` to make it work. Currently using the version `mirai: ^0.6.0`, is because you haven't released a new version with the new widget name?

**Comment by divyanshub024** [comment]
Hey @iocampomx, 

You are right. This change has not been in the release yet. Sorry for the confusion. It will be part of [0.7 release](https://github.com/Securrency-OSS/mirai/milestone/7).

For now please continue using `scrollView`.
