### ISSUE TITLE
feat: Add support for Table Widget

### ISSUE THREAD

**Issue by divyanshub024** [Securrency-OSS/mirai#272]
**Description**

Add support for the Table Widget

**Requirements**

- [ ] Create a Mirai Table Parser
- [ ] Add an example to the Mirai gallery

**Additional Context**

https://api.flutter.dev/flutter/widgets/Table-class.html

**Comment by superiorsd10** [comment]
Hello @divyanshub024 👋

I want to work on this issue, so please consider assigning it to me. 

Thank you,

**Comment by superiorsd10** [comment]
Hello @divyanshub024 👋

So I was adding the support for the `Table` widget in Mirai. I'm encountering an issue so can you please help me?

So while writing the `mirai_table` parser, there are some properties like `TableRow`, `TableColumnWidth`, and `Decoration`. Among these, the last two are abstract classes, and `Decoration` is used by the class `TableRow`. 

So I'll have to define the parse extension method on `TableRow` but what about the other two?

Will I need to define two more parsers for them without the parse extension method (because they are abstract classes)? If yes, what should be the arguments to them?

Thank you, 

_References:_

[TableRow](https://api.flutter.dev/flutter/widgets/TableRow-class.html)
[TableColumnWidth](https://api.flutter.dev/flutter/rendering/TableColumnWidth-class.html)
[Decoration](https://api.flutter.dev/flutter/painting/Decoration-class.html)

**Comment by divyanshub024** [comment]
Hey @superiorsd10,

Decoration and TableColumnWidth are the abstract classes. We need to make parsers for the sub-classes.

For decoration, we already have the [MiraiBoxDecoration](https://github.com/Securrency-OSS/mirai/blob/dev/packages/mirai/lib/src/parsers/mirai_box_decoration/mirai_box_decoration.dart) parser which you can use. 

Fpr [TableColumnWidth](https://api.flutter.dev/flutter/rendering/TableColumnWidth-class.html), we need to make parser for it's subclasses like IntrinsicColumnWidth, FlexColumnWidth, FixedColumnWidth, FractionColumnWidth. We can create a parser where depending upon the type it will select the suitable TableColumnWidth class.

**Comment by superiorsd10** [comment]
Should I do something like [MiraiInputFormatter](https://github.com/Securrency-OSS/mirai/blob/dev/packages/mirai/lib/src/parsers/mirai_input_formatters/mirai_input_formatter.dart) for `TableColumnWidth`? 

I can define the enum like in [InputFormatter](https://github.com/Securrency-OSS/mirai/blob/dev/packages/mirai/lib/src/utils/input_formatters.dart) each for the sub-classes to check the type and return the respective sub-class.

Or I will need to define a separate parser for each sub-class? If yes, then I will not need to define one for `TableColumnWidth` right as it's an abstract class?

**Comment by divyanshub024** [comment]
@superiorsd10 
I think the enum can also work but there are some [TableColumnWidth](https://api.flutter.dev/flutter/rendering/TableColumnWidth-class.html) like FractionColumnWidth that takes a value,

**Comment by divyanshub024** [comment]
Hey @superiorsd10 👋🏻 

Let me know if you are stuck anywhere or need any help :)

**Comment by superiorsd10** [comment]
Hello @divyanshub024 👋

I'm sorry for the delay in the response as I was occupied in crafting a proposal for GSoC. So I have implemented individual parsers for the sub-classes of `TableColumnWidth`.

Now I'll need to identify the type and assign the suitable sub-class. But I was wondering if should I take the enum path now.

Like I can define a `MiraiTableColumnWidth` and ask for the type, and value. Though [IntrinsicColumnWidth](https://api.flutter.dev/flutter/rendering/IntrinsicColumnWidth-class.html) takes flex. 

Then I can define an enum in utils, and define a method there that returns the appropriate sub-class based on the type. 

Is this approach good? 

Thank you,

**Comment by divyanshub024** [comment]
Hey @superiorsd10 👋🏻 

Good luck with the GSoC proposal, let me know if you need any help with that.

Yeah, the enum path sounds great! Let's try that :)

**Comment by divyanshub024** [comment]
Hey @superiorsd10, How's your GSOC going?

I just wanted to check if you are still working on this issue.
